[package]
name = "rust-schedule-api"
version = "0.1.0"
authors = ["Wilson Rodrigues <w.rodrigues@xgeeks.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rocket = "0.4.2"