FROM rustlang/rust:nightly AS builder

WORKDIR /app
COPY . .

RUN cargo install cargo-watch
RUN cargo install diesel_cli --no-default-features --features postgres

RUN cargo build

CMD ["cargo", "watch", "-x", "run"]
